/record_scene_results_node:

    config_name: 'rn50_basic'

### CLIP SCENE ESTIMATION PARAMS
/clip_scene_rec:
  ros__parameters:
    num_est_interval_samples: 19 # Number of samples 
    scene_labels: ['campus','courtyard','lab','lobby']
    scene_descriptions: ['a college campus','an outdoor courtyard','a lab', 'a lobby']
    clip_model: 'RN50'
