/record_scene_results_node:

    config_name: 'rn50_basic'

### CLIP SCENE ESTIMATION PARAMS
/clip_scene_rec:
  ros__parameters:
    num_est_interval_samples: 18 # Number of samples
    update_interval: 1. # Update after 1 second elapses
    scene_labels: ['campus','courtyard','lab','lobby']
    scene_descriptions: ['a college campus','an outdoor courtyard','a lab', 'a lobby']
    clip_model: 'RN50'

### CLIP BAYES ESTIMATOR PARAMS
/bayes_clip_scene_est:
  ros__parameters:

    scene_labels: ['campus','courtyard','lab','lobby']
    scene_prior: [.25,.25,.25,.25]

    sensor_names: ['clip']

    clip:
      obs_labels: ['campus','courtyard','lab','lobby']
      sensor_model_coeffs: [38578., 1., 76., 1.,
                            42907., 2., 1., 1.,
                            5259., 1., 36931., 5.,
                            5286., 1., 2., 36154.]
      topic: 'clip_scene_category'

### FUSED BAYES ESTIMATOR PARAMS
/bayes_fused_scene_est:
  ros__parameters:

    scene_labels: ['campus','courtyard','lab','lobby']
    scene_prior: [.25,.25,.25,.25]

    sensor_names: ['clip','dcase23']

    clip:
      obs_labels: ['campus','courtyard','lab','lobby']
      sensor_model_coeffs: [38578., 1., 76., 1.,
                            42907., 2., 1., 1.,
                            5259., 1., 36931., 5.,
                            5286., 1., 2., 36154.]
      topic: 'clip_scene_category'

    dcase23:
      obs_labels: ['airport', 'bus', 'metro', 'metro_station','park','public_square','shopping_mall','street_pedestrian','street_traffic','tram']
      sensor_model_coeffs: [13., 19., 49., 14., 206., 7., 1., 1., 37., 1941.,
                            6., 274., 9., 11., 767., 3., 2., 2., 19., 1382.,
                            16., 157., 2111., 43., 80., 2., 1., 1., 65., 31.,
                            479., 57., 191., 468., 974., 1., 68., 18., 21., 175.]
      topic: 'audio_scene_category'