version: "3"

services:

  # Bridge ROS1->ROS2 messages
  philbart_bridge_srv:

    image: philbart_bridge_img
    container_name: philbart_bridge_cont
    
    build:
      # set the build context to the directory containing build files
      context: .
      dockerfile: bridge.Dockerfile

    security_opt:
    # this is set bc of errors with RViz being denied dbus comm w/ host
      - apparmor:unconfined
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/.Xauthority:/root/.Xauthority:rw
    # give the container access to the host's network
    network_mode: host
    pid: host
    stdin_open: true
    tty: true
    entrypoint: /philbart_bridge_entrypoint.sh

  # Launch ar_track_alvar in ros1 environment
  ar_track_srv:

    image: ar_track_img
    container_name: ar_track_cont
    
    build:
      # set the build context to the directory containing build files
      context: .
      dockerfile: ar_track.Dockerfile

    environment:
      - MARKER_SIZE=15.2
      - AR_CAM_TOPIC=/oak/rgb/image_raw
      - AR_INFO_TOPIC=/oak/stereo/camera_info
      - OUTPUT_FRAME=oak_rgb_camera_optical_frame

    security_opt:
    # this is set bc of errors with RViz being denied dbus comm w/ host
      - apparmor:unconfined
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/.Xauthority:/root/.Xauthority:rw
    # give the container access to the host's network
    network_mode: host
    pid: host
    stdin_open: true
    tty: true
    entrypoint: /ar_track_entrypoint.sh

  perception_srv:
    image: perception_img
    container_name: perception_cont
    
    build:
      # set the build context to the directory containing build files
      context: .
      dockerfile: perception.Dockerfile

    # environment:
    #   - MARKER_SIZE=15.2
    #   - AR_CAM_TOPIC=/oak/rgb/image_raw
    #   - AR_INFO_TOPIC=/oak/stereo/camera_info
    #   - OUTPUT_FRAME=oak_rgb_camera_optical_frame

    entrypoint: /perception_entrypoint.sh