
services:

  # Bridge ROS1->ROS2 messages
  philbart_bridge_srv:

    image: philbart_bridge_img
    container_name: philbart_bridge_cont
    
    build:
      # set the build context to the directory containing build files
      context: .
      dockerfile: bridge.Dockerfile

    environment:
      - ROS_MASTER_URI=http://localhost:11311
      - ROS_IP=localhost

    security_opt:
    # this is set bc of errors with RViz being denied dbus comm w/ host
      - apparmor:unconfined
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/.Xauthority:/root/.Xauthority:rw
    # give the container access to the host's network
    network_mode: host
    pid: host
    stdin_open: true
    tty: true
    entrypoint: /philbart_bridge_entrypoint.sh

  # # Launch ar_track_alvar and audio_capture in ros1 environment
  # ros1_srv:

  #   image: ros1_img
  #   container_name: ros1_cont
    
  #   build:
  #     # set the build context to the directory containing build files
  #     context: .
  #     dockerfile: ros1.Dockerfile

  #   environment:
  #     - MARKER_SIZE=15.2
  #     - AR_CAM_TOPIC=/oak/rgb/image_raw
  #     - AR_INFO_TOPIC=/oak/stereo/camera_info
  #     - OUTPUT_FRAME=oak_rgb_camera_optical_frame

  #   security_opt:
  #   # this is set bc of errors with RViz being denied dbus comm w/ host
  #     - apparmor:unconfined
  #   volumes:
  #     - /tmp/.X11-unix:/tmp/.X11-unix
  #     - ${HOME}/.Xauthority:/root/.Xauthority:rw
  #   # give the container access to the host's network
  #   network_mode: host
  #   pid: host
  #   stdin_open: true
  #   tty: true
  #   entrypoint: /ros1_entrypoint.sh

  # perception_srv:
  #   image: perception_img
  #   container_name: perception_cont
    
  #   build:
  #     # set the build context to the directory containing build files
  #     context: .
  #     dockerfile: perception.Dockerfile

  #   # environment:
  #   #   - MARKER_SIZE=15.2
  #   #   - AR_CAM_TOPIC=/oak/rgb/image_raw
  #   #   - AR_INFO_TOPIC=/oak/stereo/camera_info
  #   #   - OUTPUT_FRAME=oak_rgb_camera_optical_frame

  #   entrypoint: /perception_entrypoint.sh