/**:
  ros__parameters:
    config_name: artag_role_verbal_cmd_waves_best_overall
    ssl_algo: 'WAVES'
    
    # Best overall audio params from 11 Nov eval results
    lexicon_package: 'ros_audition'
    lexicon_file: 'config/rocog_lexicon_full_phrases.txt'
    trigger_level: 7.
    am_bundle: 'WAV2VEC2_ASR_LARGE_960H'
    lm_weight: 3.
    word_score: 3.
    sil_score: 0.


### MULTIMODAL PROCESSING - SEMANTIC FUSION NODE
/semantic_fusion_node:
  ros__parameters:

    update_loop_time_sec: 0.1
    pub_loop_time_sec: 1.

    role_rec_methods: ['artag']
    command_rec_methods: ['verbal']