### UNIMODAL PROCESSING - VISION
/oak:
  ros__parameters:
    camera:
      i_enable_imu: true
      i_enable_ir: true
      i_nn_type: spatial
      i_pipeline_type: RGBD
    stereo:
      i_subpixel: true
    nn:
      i_nn_config_path: depthai_ros_driver/yolo
      i_disable_resize: true
    rgb:
      i_preview_size: 416

### UNIMODAL PROCESSING - AUDITION
audio_acq_node:
  ros__parameters:
    n_channels: 16
    src: 'plughw:1,0'
    sample_rate: 44100
    hop_size: 44100
    frame_size: 44100 # publish 1 second every second
    microphone_frame_id: 'philbart/base_link'

scene_rec_node:
  ros__parameters:
    n_channels: 16
    sample_rate: 44100
    downsample_rate: 22050
    frame_size: 441000 # Buffer 10 seconds of audio at full quality
    scene_size: 220500 # 10 seconds to classify audio
    scene_index: [0, 1]
    labels: ['indoor','outdoor','transportation']
    scene_est_interval: 1.0
    model_path: 'pretrained_models/sub2/'
    mean_path: 'config/tr_mean_676d70_f1_apd18_stereo_obj.pt'
    std_path: 'config/tr_std_676d70_f1_apd18_stereo_obj.pt'





### MULTIMODAL PROCESSING - SCENE RECOGNITION
/bayes_fused_scene_est:
  ros__parameters:

    scene_labels: ['campus','courtyard','lab','lobby']
    scene_prior: [.25,.25,.25,.25]

    sensor_names: ['clip','dcase23']

    clip:
      obs_labels: ['college-campus','courtyard','laboratory','lobby']
      sensor_model_coeffs: [25008., 5984., 1., 7663.,
                            41098., 1758., 1., 54.,
                            1., 1., 25794., 16400.,
                            1., 1., 1., 41440.]
      topic: 'clip_scene_category'

    dcase23:
      obs_labels: ['airport', 'bus', 'metro', 'metro_station','park','public_square','shopping_mall','street_pedestrian','street_traffic','tram']
      sensor_model_coeffs: [15., 16., 42., 10., 196., 5., 2., 2., 56., 1944.,
                            3., 288., 11., 11., 796., 2., 1., 2., 11., 1350.,
                            11., 171., 2110., 41., 81., 1., 1., 1., 64., 26.,
                            457., 57., 205., 481., 977., 2., 70., 17., 20., 166.]
      topic: 'audio_scene_category'