semantic_tracking_node:
  ros__parameters:

    loop_time_sec: 1.

    objects_of_interest: ['person']

    person:
      det_thresh: .15
      del_thresh: .25
      score_decay: .05

      state_timeout: 10.

      attributes:
        variables: ['age','gender']
        age:
          labels: ['unknown','baby','toddler','child','young_adult','adult','elder']
          probs: [10., 1., 1., 1., 1., 1., 1.]
          sensor_model_coeffs: [.8, .033, .033, .033, .033, .033, .033,
                                .033, .8, .033, .033, .033, .033, .033,
                                .033, .033, .8, .033, .033, .033, .033,
                                .033, .033, .033, .8, .033, .033, .033,
                                .033, .033, .033, .033, .8, .033, .033,
                                .033, .033, .033, .033, .033, .8, .033,
                                .033, .033, .033, .033, .033, .033, .8]

        gender:
          labels: ['unknown','male','female','nonbinary']
          probs: [10., 1., 1., 1.]
          sensor_model_coeffs: [.65, .117, .117, .117,
                                .117, .65, .117, .117,
                                .117, .117, .65, .117,
                                .117, .117, .117, .65]

      states:
        variables: ['role','movement','emotion']
        role:
          labels: ['unknown','civilian','military']
          probs: [10., 1., 1.]
          sensor_model_coeffs: [.6, .2, .2,
                                .2, .6, .2,
                                .2, .2, .6]

        movement:
          labels: ['unknown','sitting','standing','walking','running']
          probs: [10., 1., 1., 1., 1.]
          sensor_model_coeffs: [.7, .075, .075, .075, .075,
                                .075, .7, .075, .075, .075,
                                .075, .075, .7, .075, .075,
                                .075, .075, .075, .7, .075,
                                .075, .075, .075, .075, .7]
        emotion:
          labels: ['unknown','happy','sad','angry','neutral']
          probs: [10., 1., 1., 1., 1.]
          sensor_model_coeffs: [.6, .1, .1, .1, .1,
                                .1, .6, .1, .1, .1,
                                .1, .1, .6, .1, .1,
                                .1, .1, .1, .6, .1,
                                .1, .1, .1, .1, .6]
                                


clip_vis_rec_server:
  ros__parameters:

    clip_model: 'ViT-B/32'

    object_classes: ['person']

    person:
      attributes:
        variables: ['age','gender']
        age:
          labels: ['unknown','baby','toddler','child','young_adult','adult','elder']
          descriptions: ['a person of unknown age','a baby','a toddler','a child','a young adult','an adult','an elderly adult']
        gender:
          labels: ['unknown','male','female','nonbinary']
          descriptions: ['a person of unknown gender','a male person','a female person','a nonbinary person']

      states:
        variables: ['role','movement','emotion']
        role:
          labels: ['unknown','civilian','military']
          descriptions: ['a person', 'a civilian person','a person in the military']
        movement:
          labels: ['unknown','sitting', 'standing','walking','running']
          descriptions: ['a person','a person sitting down', 'a person standing', 'a person walking','a person running']
        emotion:
          labels: ['unknown','happy','sad','angry','neutral']
          descriptions: ['a person with unknown emotion','a happy person','a sad person','an angry person','a person with neutral emotion']