/**:
  ros__parameters:

    loop_time_sec: 1.
    objects_of_interest: ['person']
    clip_model: 'ViT-B/32'
    object_classes: ['person']

    upper_prob_limit: .99
    lower_prob_limit: .01

    ang_match_threshold: .524 # ! 30 degrees

    person:
      # det_thresh: .15
      # del_thresh: .25
      # score_decay: .05

      # state_timeout: 0.5

      attributes:
        variables: ['age','gender']
        age:
          labels: ['unknown','baby','toddler','child','young_adult','adult','elder']
          descriptions: ['a person of unknown age','a baby','a toddler','a child','a young adult','an adult','an elderly adult']
          probs: [10., 1., 1., 1., 1., 1., 1.]
          sensor_model_coeffs: [.8, .033, .033, .033, .033, .033, .033,
                                .033, .8, .033, .033, .033, .033, .033,
                                .033, .033, .8, .033, .033, .033, .033,
                                .033, .033, .033, .8, .033, .033, .033,
                                .033, .033, .033, .033, .8, .033, .033,
                                .033, .033, .033, .033, .033, .8, .033,
                                .033, .033, .033, .033, .033, .033, .8]
          update_method: 'confidence'
          update_threshold: .95

        gender:
          labels: ['unknown','male','female','nonbinary']
          descriptions: ['a person of unknown gender','a male person','a female person','a nonbinary person']
          probs: [10., 1., 1., 1.]
          sensor_model_coeffs: [.65, .117, .117, .117,
                                .117, .65, .117, .117,
                                .117, .117, .65, .117,
                                .117, .117, .117, .65]
          update_method: 'confidence'
          update_threshold: .95

      states:
        variables: ['role','movement','emotion']
        role:
          labels: ['unknown','civilian','military','scientist','robot_supervisor']
          descriptions: ['a person', 'a civilian person','a person wearing a military uniform', 'a person wearing a lab coat','a person wearing a yellow reflective safety vest']
          probs: [10., 1., 1., 1., 1.]
          sensor_model_coeffs: [.6, .1, .1, .1, .1,
                                .1, .6, .1, .1, .1,
                                .1, .1, .6, .1, .1,
                                .1, .1, .1, .6, .1,
                                .1, .1, .1, .1, .6]
          update_method: 'time'
          update_threshold: .75
          
        movement:
          labels: ['unknown','sitting','standing','walking','running']
          descriptions: ['a person','a person sitting down', 'a person standing', 'a person walking','a person running']
          probs: [10., 1., 1., 1., 1.]
          sensor_model_coeffs: [.7, .075, .075, .075, .075,
                                .075, .7, .075, .075, .075,
                                .075, .075, .7, .075, .075,
                                .075, .075, .075, .7, .075,
                                .075, .075, .075, .075, .7]
          update_method: 'time'
          update_threshold: .75

        emotion:
          labels: ['unknown','happy','sad','angry','neutral']
          descriptions: ['a person with unknown emotion','a happy person','a sad person','an angry person','a person with neutral emotion']
          probs: [10., 1., 1., 1., 1.]
          sensor_model_coeffs: [.6, .1, .1, .1, .1,
                                .1, .6, .1, .1, .1,
                                .1, .1, .6, .1, .1,
                                .1, .1, .1, .6, .1,
                                .1, .1, .1, .1, .6]
          update_method: 'time'
          update_threshold: .75

      comms:
        labels: ['none','other','advance','attention','follow-me','halt','move-forward','move-in-reverse','rally']
        transcripts: ['','*','advance','attention','follow me','halt','move forward','move in reverse','rally']
        probs: [10., 1., 1., 1., 1., 1., 1., 1., 1.]
        # p(command_detected|command_issued)
        sensor_model_coeffs: [.92, .01, .01, .01, .01, .01, .01, .01, .01,
                              .01, .92, .01, .01, .01, .01, .01, .01, .01,
                              .01, .01, .92, .01, .01, .01, .01, .01, .01,
                              .01, .01, .01, .92, .01, .01, .01, .01, .01,
                              .01, .01, .01, .01, .92, .01, .01, .01, .01,
                              .01, .01, .01, .01, .01, .92, .01, .01, .01,
                              .01, .01, .01, .01, .01, .01, .92, .01, .01,
                              .01, .01, .01, .01, .01, .01, .01, .92, .01,
                              .01, .01, .01, .01, .01, .01, .01, .01, .92]